create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  full_name text not null,
  phone text not null,
  email text,
  preferred_location text not null default 'manuel_plaza',
  source text not null default 'pulpo_box_landing',
  user_agent text,
  status text not null default 'new'
);

alter table public.leads enable row level security;

grant insert, select, update, delete on public.leads to service_role;

create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_status_idx on public.leads (status);
